### ISSUE TITLE
internal_error : Internal server error occurs

### ISSUE THREAD

**Issue by Bits101** [GluuFederation/gluu-magento-sso-login-extension#1]
Hi,

After following the instructions in the readme file. I am getting this message.
1) Gluu server is installed and working
2) Magento extension is installed and working
3) I have run the oxd-server and its running without any errors. 

But when I click on NEXT in the magento extension I get this error

"internal_error : Internal server error occurs"

Can you tell me what wrong?

Much appreciated!

**Comment by willow9886** [comment]
Hi there, 

Are you following [these instructions](https://gluu.org/docs-oxd/plugin/php/cms/magento/) ?

Thanks,
Will

**Comment by xohaib123** [comment]
Hi,

Thankyou for your quick reply. 
Yes I have followed these instructions..... currently the port 8099 is listening to it 

" Server socket is bound to port: 8099 "

and now in magento admin panel I am getting a blank page (attaching a snapshot)

[http://www.tiikoni.com/tis/view/?id=be59a56](url)

**Comment by willow9886** [comment]
OK, @dollar007 should be able to help troubleshoot. Thanks for kicking the tires on this!

**Comment by dollar007** [comment]
@willow9886 @xohaib123 @nynymike 
The problem is with the versions of extension/gluu-server/oxd server. If you use 2.4.2 for all the version must be the same. Please read the instruction attentively.

**Comment by xohaib123** [comment]
@dollar007 I am using 2.4.3 for both the extension and oxd server.

Right now the magento extension is showing an empty page when I click on Gluu SSO in magento backend.

**Comment by xohaib123** [comment]
I solved this issue by disabling this "Admin routing compatibility mode for extensions: Disabled" in system configuration. Basically this magento extension is not compatible to magento's new admin routing.

Now I am getting this error  "internal_error : Internal server error occurs"

oxd-server 2.4.2
magento sso extension is also 2.4.2

**Comment by dollar007** [comment]
@xohaib123 can You send me your oxd-server .log file, which is located in bin folder

**Comment by xohaib123** [comment]
Here you go
[oxd-server.zip](https://github.com/GluuFederation/gluu-magento-sso-login-extension/files/197339/oxd-server.zip)

**Comment by dollar007** [comment]
@xohaib123 your site is not https://

**Comment by Bits101** [comment]
@dollar007 I am afraid not. I thought only gluu server needs https. Is this required?

**Comment by dollar007** [comment]
@Bits101 It is required for oxd-server.

**Comment by yuriyz** [comment]
"https" is required for "web" application_type.

**Comment by nynymike** [comment]
It would be nice if a more informative error page was displayed...

**Comment by dollar007** [comment]
@nynymike @yuriyz 
if I am not mistaken all problems or errors connected with oxd-server is showing this error (internal_error : Internal server error occurs), without unsupported error

**Comment by Bits101** [comment]
@dollar007 @yuriyz Thanks guys.. enabling "https" solved the issue.

**Comment by Bits101** [comment]
I'll be uploading a zip file soon here with admin routing compatibility for latest magento's

**Comment by dollar007** [comment]
@Bits101 
always ready to help and support
