### ISSUE TITLE
 All the user list?

### ISSUE THREAD

**Issue by Bits101** [GluuFederation/gluu-magento-sso-login-extension#2]
Hi @dollar007,

In Gluu server, how can I view all the users who are in "Manage people"
Currently I have to search for each user's name or email.

How can I see all the user list?

**Comment by Bits101** [comment]
also i am updating this code to work with latest magento CE 1.9.X and EE 1.14.X and will be updating its look and feel as well so it looks like original magento style.

Is this ok with you guys?

**Comment by mzico** [comment]
@Bits101 you can do a quick ldapsearch in Gluu-ldap to see all people under 'ou=people,o=inum_of_your_gluu_server,o=gluu'
